FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY edge_simulator ./edge_simulator
COPY domain ./domain
COPY shared ./shared

CMD ["python", "-m", "edge_simulator.simulator", "--backend-url", "http://backend:8765"]
